name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mthaller/adventrunner:${{ github.sha }}
      - name: Publish image
        run: docker push mthaller/adventrunner:${{ github.sha }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'adventrunner'
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          images: 'mthaller/adventrunner:${{ github.sha }}'