export const RESET_CALENDAR = "RESET_CALENDAR_ACTION";
export const OPEN_DOOR = "OPEN_DOOR_ACTION"
export const MARK_DOOR_DONE = "MARK_DOOR_DONE_ACTION"
export const GET_CALENDAR = "GET_CALENDAR_ACTION"
export const GET_AUTH_HEADERS = "GET_AUTH_HEADERS_ACTION"
export const SET_SCALE_FACTOR = "SET_SCALE_FACTOR_ACTION"
export const SET_CALENDAR = "SET_CALENDAR_ACTION"
export const SET_CURRENT_PERIOD = "SET_CURRENT_PERIOD_ACTION"